### ISSUE TITLE
[New Instance]: listen-spotify.whateveritworks.org

### ISSUE THREAD

**Issue by xbdmHQ** [nesaku/SpotifyInfo#2]
**What URL Is Your Instance Available At?**
https://listen-spotify.whateveritworks.org/

**What Country Is Your Instance Being Hosted In?**
Germany

**What Hosting Provider Is Used? (Input Your ISP's Name If You Are Self-Hosting)**
ISP: Hetzner
CDN: Cloudflare

**Do You Collect Any User Data?**
no

**Contact Details**
support@whateveritworks.org (email is not setup yet)

**Comment by nesaku** [comment]
Added, thanks for hosting.
